---
language: python
python: "2.7"
sudo: yes
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install apt-transport-https

install:
  - sudo pip install ansible

  # install requirements
  - sudo ansible-galaxy install -r ansible/requirements.yml

  # setup ansible hosts
  - sudo bash -c 'printf "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts'


script:

  # test and execute playbook
  - sudo ansible-playbook ansible/playbook.yml --syntax-check
  - sudo ansible-playbook ansible/playbook.yml --connection=local

  # validate everything installed
  - which idea
  - which soapui
  - which meld
  - which gnome-system-monitor
  - which guake

  # check versions
  - java -version
  - docker --version
  - google-chrome --version
  - git --version

  # check user is created
  - getent passwd neito
  - grep -Po "^sudo.+:\K.*$" /etc/group | grep neito
