---
language: python
python: "2.7"
sudo: yes

before_install:
  - sudo apt-get update -qq

install:
  - sudo pip install ansible

script:
  # install requirements
  - sudo ansible-galaxy install -r ansible/requirements.yml

  # test and execute playbook
  - sudo ansible-playbook ansible/playbook.yml --syntax-check
  - sudo ansible-playbook ansible/playbook.yml --connection=local

  # validate everything installed
  - which idea
  - which soapui
  - which meld
  - which gnome-system-monitor
  - which guake

  # check versions
  - java -version
  - docker --version
  - google-chrome --version
  - git --version

  # check user is created
  - getent passwd neito
  - grep -Po "^sudo.+:\K.*$" /etc/group | grep neito
